[workspace]
members = ["server", "client", "brain"]

resolver = "2"

[package]
name = "avatar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
brain = { path = "./brain" }
serde_json = "1.0.96"
serde = { version = "1.0.164", features = ["derive"] }
anyhow = "1.0.71"
pyo3 = { version = "0.19.0", features = ["auto-initialize"] }
serialport = { version = "4.2.1", default-features = false }
tokio = { version = "1.28.2", features = [
    "signal",
    "rt-multi-thread",
    "macros",
] }
dotenvy = "0.15.7"
reqwest = { version = "0.11.18", default-features = false, features = [
    "json",
    "rustls-tls",
] }
network-interface = "1.0.1"
ractor = "0.8.4"
async-trait = "0.1.68"
