apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: robotic-avatar
spec:
  environments:
    - name: prod
      build:
        from: main
  components:
    - name: web
      secrets:
        - AVATAR_TOKEN_KEY
        - AVATAR_AZURE_AD_SECRET
        - AVATAR_ICE
      variables:
        AVATAR_AZURE_AD_ID: ""
        AVATAR_AZURE_AD_URL: ""
        AVATAR_BIND_ADDRESS: "0.0.0.0:8080"
      src: .
      ports:
        - name: http
          port: 8080
      publicPort: http
      public: true
      environmentConfig:
        - environment: prod
          monitoring: false
          replicas: 1