name: Rust

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check format
      run: cargo fmt --check --verbose
    - name: Check compile errors
      run: cargo check --verbose
    - name: Run lints
      run: cargo clippy --verbose
    - name: Run tests
      run: cargo test --verbose